import type { CategoriaPubblica, SpecificheTecniche, VeicoloPubblico } from "@/types/veicolo";
import { mergeSpecifiche } from "@/lib/specifiche-tecniche-utils";

export const DEMO_CATEGORIE: CategoriaPubblica[] = [
  { id: "cat-auto", nome: "Auto", slug: "auto", ordine: 1 },
  { id: "cat-pulmini", nome: "Pulmini 9 posti", slug: "pulmini-9-posti", ordine: 2 },
  { id: "cat-furg-piccoli", nome: "Furgoni Piccoli", slug: "furgoni-piccoli", ordine: 3 },
  { id: "cat-furg-medi", nome: "Furgoni Medi", slug: "furgoni-medi", ordine: 4 },
  { id: "cat-furg-grandi", nome: "Furgoni Grandi", slug: "furgoni-grandi", ordine: 5 },
  {
    id: "cat-furg-grandi-citta",
    nome: "Furgoni Grandi (Uso Città)",
    slug: "furgoni-grandi-citta",
    ordine: 6,
  },
  { id: "cat-furg-xl", nome: "Furgoni XL", slug: "furgoni-xl", ordine: 7 },
];

function cat(slug: string): CategoriaPubblica {
  const found = DEMO_CATEGORIE.find((c) => c.slug === slug);
  if (!found) throw new Error(`Categoria demo mancante: ${slug}`);
  return found;
}

/** Foto reali LILO (salvate in public/images/flotta/) — niente stock errate */
const DEMO_IMAGES = {
  auto: "/images/veicoli/volvo-s40-noleggio-trieste.webp",
  autoRetro: "/images/veicoli/volvo-s40-retro-trieste.webp",
  autoGuida: "/images/veicoli/volvo-s40-interni-guida.webp",
  autoSediliPosteriori: "/images/veicoli/volvo-s40-sedili-posteriori.webp",
  citroenC3: "/images/veicoli/citroen-c3-grigia-trieste.webp",
  citroenC3Retro: "/images/veicoli/citroen-c3-grigia-retro.webp",
  citroenC3Guida: "/images/veicoli/citroen-c3-interni-guida.webp",
  citroenC3Posteriori: "/images/veicoli/citroen-c3-interni-posteriori.webp",
  pulmino: "/images/veicoli/renault-trafic-9-posti-noleggio-trieste.webp",
  pulminoGuida: "/images/veicoli/renault-trafic-9-posti-guida.webp",
  pulminoAbitacolo: "/images/veicoli/renault-trafic-9-posti-abitacolo.webp",
  pulminoFileSedili: "/images/veicoli/renault-trafic-9-posti-file-sedili.webp",
  pulminoPosteriore: "/images/veicoli/renault-trafic-9-posti-posteriore-trieste.webp",
  nissanPrimastarFrontale: "/images/veicoli/nissan-primastar-9-posti-frontale.webp",
  nissanPrimastarRetro: "/images/veicoli/nissan-primastar-9-posti-retro.webp",
  nissanPrimastarGuida: "/images/veicoli/nissan-primastar-9-posti-guida.webp",
  nissanPrimastarInterni: "/images/veicoli/nissan-primastar-9-posti-interni.webp",
  furgonePiccolo: "/images/veicoli/fiat-doblo-noleggio-furgoni-piccoli-trieste.webp",
  toyotaProaceCity: "/images/flotta/furgone-piccolo-toyota-proace-city-trieste-front.webp",
  toyotaProaceCityRear: "/images/flotta/furgone-piccolo-toyota-proace-city-trieste-rear.webp",
  furgoneMedio: "/images/veicoli/ford-transit-custom-noleggio-furgoni-medi-trieste.webp",
  citroenJumpyFr523sw: "/images/veicoli/citroen-jumpy-noleggio-furgoni-medi-trieste.webp",
  citroenJumpyFr523swPosteriore: "/images/veicoli/citroen-jumpy-noleggio-lilo-trieste-posteriore.webp",
  fiatDucatoL1h1: "/images/veicoli/fiat-ducato-l1h1-noleggio-trieste.webp",
  fiatDucatoL1h1Rampa: "/images/veicoli/fiat-ducato-l1h1-rampa-moto-haccp.webp",
  fiatDucatoL1h1Posteriore: "/images/veicoli/fiat-ducato-l1h1-posteriore-noleggio-trieste.webp",
  fordTransitL2h2: "/images/veicoli/ford-transit-l2h2-noleggio-trieste.webp",
  fordTransitL2h2Retro: "/images/veicoli/ford-transit-l2h2-retro-trieste.webp",
  citroenJumperL2h2: "/images/veicoli/furgone-citroen-jumper-l2h2-trieste.webp",
  citroenJumperL2h2Retro: "/images/veicoli/furgone-citroen-jumper-l2h2-retro.webp",
  opelVivaro: "/images/veicoli/furgone-opel-vivaro-trieste.webp",
  opelVivaroRetro: "/images/veicoli/furgone-opel-vivaro-retro.webp",
  furgoneGrande: "/images/flotta/furgone-grande-iveco-daily-l2h2-trieste-front.webp",
  furgoneGrandeRetro: "/images/flotta/furgone-grande-iveco-daily-l2h2-trieste-rear.webp",
  furgoneXl: "/images/veicoli/ford-transit-l3h2-passo-lungo-noleggio.webp",
  peugeotBoxerL3h3: "/images/veicoli/furgone-peugeot-boxer-l3h3-trieste.webp",
  peugeotBoxerL3h3Retro: "/images/veicoli/furgone-peugeot-boxer-l3h3-retro.webp",
} as const;

function specs(partial: Partial<SpecificheTecniche>): SpecificheTecniche {
  return mergeSpecifiche(partial);
}

function demoFoto(
  id: string,
  url: string,
  alt: string,
  copertina = true,
): VeicoloPubblico["foto"][number] {
  return {
    id,
    url_pubblico: url,
    alt_text: alt,
    titolo: null,
    didascalia: null,
    ordine: 0,
    is_copertina: copertina,
  };
}

/** Dati dimostrativi quando Supabase non è ancora configurato. */
export const DEMO_VEICOLI: VeicoloPubblico[] = [
  {
    id: "demo-auto-1",
    slug: "volvo-s40",
    targa: "VS40TS",
    marca: "Volvo",
    modello: "S40",
    versione: "Berlina",
    anno_immatricolazione: 2011,
    colore: "Nero",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 5,
    porte: 4,
    titolo_pubblico: "Volvo S40 — Noleggio berlina Trieste",
    sottotitolo: "Eleganza, comfort e sicurezza per lavoro e turismo",
    descrizione_breve:
      "Noleggio Volvo S40 a Trieste: berlina premium nera, ideale per viaggi d'affari e turismo. Ritiro in Viale Campi Elisi 38/b.",
    descrizione_completa:
      "La Volvo S40 è la berlina premium di LILO Autonoleggio a Trieste: elegante e confortevole per viaggi di lavoro, cerimonie o spostamenti a lungo raggio. Offre i rinomati sistemi di sicurezza Volvo, interni curati con consolle centrale ultra-sottile e sedili ergonomici. Ritiro immediato presso la sede di Viale Campi Elisi 38/b.",
    seo_title: "Noleggio Volvo S40 Trieste | Berlina Premium | LILO",
    seo_description:
      "Noleggia la Volvo S40 a Trieste (Viale Campi Elisi 38/b). Berlina elegante per lavoro e turismo. LILO Autonoleggio.",
    seo_keywords: ["noleggio volvo trieste", "berlina noleggio trieste", "volvo s40"],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.auto,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Volvo S40 — berlina premium a noleggio a Trieste presso LILO Autonoleggio, Viale Campi Elisi 38/b.",
    ai_highlights: [
      "Eleganza e Comfort: Berlina premium ideale per viaggi di lavoro, cerimonie o spostamenti a lungo raggio nel massimo relax.",
      "Sicurezza Volvo: Dotata dei rinomati sistemi di sicurezza attiva e passiva del marchio svedese.",
      "Interni Curati: Salotto di bordo accogliente con consolle centrale ultra-sottile e sedili ad altissimo livello di ergonomia.",
      "Ritiro in Sede: Disponibile per il ritiro immediato presso LILO Autonoleggio in Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "La Volvo S40 è adatta ai viaggi di lavoro?",
        a: "Sì: è una berlina premium confortevole, ideale per trasferte, cerimonie e spostamenti a lungo raggio.",
      },
      {
        q: "Dove ritiro l’auto?",
        a: "Presso LILO Autonoleggio in Viale Campi Elisi 38/b, Trieste.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("auto"),
    specifiche_tecniche: specs({
      trazione: "Anteriore",
      sensori_parcheggio: true,
      lunghezza_mm: 4476,
      larghezza_mm: 1770,
      altezza_mm: 1452,
      capacita_bagagliaio_valigie: 3,
      classe_ambientale: "Euro 5",
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 45,
        valuta: "EUR",
        descrizione: "100 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      {
        id: "demo-volvo-copertina",
        url_pubblico: DEMO_IMAGES.auto,
        alt_text:
          "Noleggio berlina Volvo S40 nera a Trieste presso LILO Autonoleggio in Viale Campi Elisi 38/b",
        titolo: "Volvo S40 noleggio auto Trieste Viale Campi Elisi",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-volvo-retro",
        url_pubblico: DEMO_IMAGES.autoRetro,
        alt_text:
          "Vista posteriore Volvo S40 elegante ideale per viaggi d'affari e turismo a Trieste",
        titolo: "Noleggio Volvo S40 berlina Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
      {
        id: "demo-volvo-guida",
        url_pubblico: DEMO_IMAGES.autoGuida,
        alt_text: "Posto guida ed eleganti interni con consolle fluttuante Volvo S40",
        titolo: "Interni e plancia Volvo S40",
        didascalia: null,
        ordine: 2,
        is_copertina: false,
      },
      {
        id: "demo-volvo-sedili",
        url_pubblico: DEMO_IMAGES.autoSediliPosteriori,
        alt_text: "Sedili posteriori confortevoli ed eleganti per passeggeri Volvo S40",
        titolo: "Comfort passeggeri Volvo S40",
        didascalia: null,
        ordine: 3,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-citroen-c3",
    slug: "citroen-c3",
    targa: "C3-ND-01",
    marca: "Citroën",
    modello: "C3",
    versione: "Utilitaria",
    anno_immatricolazione: 2019,
    colore: "Grigio metallizzato",
    alimentazione: "Benzina",
    cambio: "Manuale",
    posti: 5,
    porte: 5,
    titolo_pubblico: "Citroën C3 — Noleggio auto utilitaria Trieste",
    sottotitolo: "City-car compatta, moderna e comoda per Trieste e dintorni",
    descrizione_breve:
      "Noleggio Citroën C3 a Trieste: utilitaria grigio metallizzato, ideale per città e spostamenti quotidiani. Ritiro in Viale Campi Elisi 38/b.",
    descrizione_completa:
      "La Citroën C3 è la city-car utilitaria di LILO S.r.l.: design iconico, dimensioni ideali per muoversi e parcheggiare nel centro di Trieste, consumi contenuti e comfort Advanced Comfort con sedili accoglienti e plancia intuitiva. Perfetta per spostamenti urbani ed extraurbani. Ritiro e riconsegna presso la sede di Viale Campi Elisi 38/b a Trieste.",
    seo_title: "Noleggio Citroën C3 Trieste | Auto Utilitaria | LILO Autonoleggio",
    seo_description:
      "Noleggia la Citroën C3 a Trieste (Viale Campi Elisi 38/b). City-car compatta, consumi ridotti e comfort Advanced Comfort. LILO Autonoleggio.",
    seo_keywords: [
      "noleggio citroen c3 trieste",
      "noleggio auto utilitaria trieste",
      "city car noleggio trieste",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.citroenC3,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Citroën C3 — utilitaria city-car a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b.",
    ai_highlights: [
      "🚗 City-Car Compatta e Moderna: Design iconico, dimensioni ideali per muoversi e parcheggiare agevolmente nel centro di Trieste.",
      "⛽ Consumi Ridotti ed Efficienza: Motorizzazione brillante e dai consumi contenuti, perfetta per spostamenti urbani ed extraurbani.",
      "🛋️ Comfort di Bordo Advanced Comfort: Sedili accoglienti, plancia intuitiva e guida riposante anche su lunghi tragitti.",
      "📍 Ritiro e Consegna in Sede: Presso la sede LILO S.r.l. di Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "Dove ritiro la Citroën C3?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
      {
        q: "È adatta al centro città?",
        a: "Sì: dimensioni compatte e consumi contenuti, ideale per muoversi e parcheggiare a Trieste.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("auto"),
    specifiche_tecniche: specs({
      trazione: "Anteriore",
      sensori_parcheggio: true,
      capacita_bagagliaio_valigie: 2,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 40,
        valuta: "EUR",
        descrizione: "100 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      {
        id: "demo-c3-copertina",
        url_pubblico: DEMO_IMAGES.citroenC3,
        alt_text:
          "Noleggio autovettura Citroën C3 grigio metallizzato a Trieste presso LILO Autonoleggio in Viale Campi Elisi 38/b",
        titolo: "Citroën C3 noleggio auto Trieste",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-c3-retro",
        url_pubblico: DEMO_IMAGES.citroenC3Retro,
        alt_text:
          "Vista laterale e posteriore Citroën C3 per noleggio a breve e medio termine a Trieste",
        titolo: "Noleggio Citroën C3 utilitaria Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
      {
        id: "demo-c3-guida",
        url_pubblico: DEMO_IMAGES.citroenC3Guida,
        alt_text: "Posto di guida moderno e plancia ergonomica Citroën C3",
        titolo: "Interni e posto guida Citroën C3",
        didascalia: null,
        ordine: 2,
        is_copertina: false,
      },
      {
        id: "demo-c3-posteriori",
        url_pubblico: DEMO_IMAGES.citroenC3Posteriori,
        alt_text: "Sedili posteriori confortevoli e abitacolo spazioso Citroën C3",
        titolo: "Abitacolo e sedili posteriori Citroën C3",
        didascalia: null,
        ordine: 3,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-pulmini-1",
    slug: "renault-trafic-9-posti",
    targa: "GL555YT",
    marca: "Renault",
    modello: "Trafic",
    versione: "9 posti",
    anno_immatricolazione: 2020,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 9,
    porte: 5,
    titolo_pubblico: "Renault Trafic 9 posti — Noleggio pulmino Trieste",
    sottotitolo: "Comfort, accesso agevolato e interni sempre igienizzati",
    descrizione_breve:
      "Noleggio Renault Trafic 9 posti a Trieste: pulmino diesel con posto guida confortevole, portellone scorrevole e interni igienizzati. Ritiro in Viale Campi Elisi 38/b. Targa GL555YT.",
    descrizione_completa:
      "Il Renault Trafic 9 posti (targa GL555YT) è il pulmino ideale per gruppi, gite ed eventi a Trieste. Offre posto guida ergonomico con bracciolo e plancia moderna, ampio portellone scorrevole con gradino d'ingresso ribassato, interni in tessuto ad alta resistenza e tappetini in gomma lavabili, sempre igienizzati prima di ogni noleggio. Ritiro e riconsegna presso LILO S.r.l., Viale Campi Elisi 38/b.",
    seo_title: "Noleggio Renault Trafic 9 posti Trieste | Pulmino LILO",
    seo_description:
      "Noleggia il Renault Trafic 9 posti a Trieste (Viale Campi Elisi 38/b). Comfort, accesso agevolato e interni igienizzati. LILO Autonoleggio.",
    seo_keywords: ["noleggio pulmino 9 posti trieste", "renault trafic noleggio", "GL555YT"],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.pulmino,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Renault Trafic 9 posti — pulmino a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b. Targa GL555YT.",
    ai_highlights: [
      "Comfort Anteriore: Posto guida ergonomico con bracciolo e plancia moderna dotata di vani portaoggetti capienti.",
      "Accesso Agevolato: Ampio portellone scorrevole e gradino d'ingresso ribassato per salire comodamente a bordo.",
      "Igiene e Pulizia: Interni in tessuto ad alta resistenza e tappetini in gomma lavabili, sempre igienizzati prima di ogni noleggio.",
    ],
    ai_faq: [
      {
        q: "Quanti passeggeri porta il Renault Trafic?",
        a: "Fino a 9 posti, ideale per gruppi, gite ed eventi.",
      },
      {
        q: "Dove ritiro il pulmino?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("pulmini-9-posti"),
    specifiche_tecniche: specs({
      portata_kg: 900,
      volume_carico_mc: null,
      trazione: "Anteriore",
      passo: "Normale",
      tetto: "Alto",
      sensori_parcheggio: true,
      lunghezza_mm: 5300,
      larghezza_mm: 1956,
      altezza_mm: 1971,
      configurazione_sedili: "3+3+3",
      climatizzazione_posteriore: true,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 90,
        valuta: "EUR",
        descrizione: "150 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      {
        id: "demo-trafic-copertina",
        url_pubblico: DEMO_IMAGES.pulmino,
        alt_text: "Noleggio Renault Trafic 9 posti LILO Autonoleggio Viale Campi Elisi 38/b Trieste",
        titolo: "Renault Trafic 9 posti — esterno Trieste",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-trafic-guida",
        url_pubblico: DEMO_IMAGES.pulminoGuida,
        alt_text: "Posto di guida confortevole e plancia Renault Trafic 9 posti noleggio a Trieste",
        titolo: "Plancia e posto guida Renault Trafic 9 posti",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
      {
        id: "demo-trafic-file-sedili",
        url_pubblico: DEMO_IMAGES.pulminoFileSedili,
        alt_text:
          "Configurazione file di sedili posteriori per pulmino 9 posti ideale per gruppi a Trieste",
        titolo: "Spazio e comodi sedili posteriori Renault Trafic",
        didascalia: null,
        ordine: 2,
        is_copertina: false,
      },
      {
        id: "demo-trafic-posteriore",
        url_pubblico: DEMO_IMAGES.pulminoPosteriore,
        alt_text: "Vista posteriore Renault Trafic 9 posti noleggio Trieste LILO",
        titolo: "Renault Trafic 9 posti — posteriore",
        didascalia: null,
        ordine: 3,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-nissan-primastar-9-posti",
    slug: "nissan-primastar-9-posti",
    targa: "GK420DW",
    marca: "Nissan",
    modello: "Primastar",
    versione: "9 posti Combi",
    anno_immatricolazione: 2018,
    colore: "Grigio metallizzato",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 9,
    porte: 5,
    titolo_pubblico: "Nissan Primastar 9 posti — Pulmino Trieste",
    sottotitolo: "Combi 9 posti per gruppi, trasferte e vacanze in famiglia",
    descrizione_breve:
      "Noleggio Nissan Primastar 9 posti a Trieste: pulmino Combi grigio metallizzato, vano bagagli capiente. Ritiro in Viale Campi Elisi 38/b. Targa GK420DW.",
    descrizione_completa:
      "Il Nissan Primastar 9 posti Combi (targa GK420DW) è il pulmino LILO S.r.l. per trasporto persone: spazio full-comfort per trasferte aziendali, gruppi sportivi e vacanze in famiglia, con vano bagagli capiente per valigie e attrezzature. Posizione di guida rialzata e interni sanificati prima di ogni consegna. Ritiro e riconsegna presso la sede di Viale Campi Elisi 38/b a Trieste.",
    seo_title: "Noleggio Nissan Primastar 9 posti Trieste | Pulmini | LILO",
    seo_description:
      "Noleggia il Nissan Primastar 9 posti a Trieste (Viale Campi Elisi 38/b). Pulmino Combi per gruppi e vacanze. LILO Autonoleggio.",
    seo_keywords: [
      "noleggio nissan primastar trieste",
      "pulmino 9 posti trieste",
      "noleggio combi trieste",
      "GK420DW",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.nissanPrimastarFrontale,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Nissan Primastar 9 posti Combi — pulmino a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b. Targa GK420DW.",
    ai_highlights: [
      "👥 9 Posti Full-Comfort: Spazio abbondante per tutti i passeggeri, ideale per trasferte aziendali, gruppi sportivi o vacanze in famiglia.",
      "🧳 Vano Bagagli Capiente: Ampio volume di carico posteriore per valigie ingombranti e attrezzature sportive.",
      "🛡️ Tecnologia e Sicurezza Nissan: Posizione di guida rialzata, visibilità ottima e moderni sistemi di assistenza alla guida.",
      "🧼 Sanificazione Garantita: Interni igienizzati a fondo prima di ogni consegna per la massima sicurezza dei passeggeri.",
      "📍 Ritiro in Sede: Disponibile presso la sede LILO Autonoleggio di Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "Dove ritiro il Nissan Primastar 9 posti?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
      {
        q: "Quanti passeggeri può trasportare?",
        a: "Fino a 9 posti (autista incluso), ideale per gruppi e famiglie.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b. Cauzione solo carta.",
    categoria: cat("pulmini-9-posti"),
    specifiche_tecniche: specs({
      trazione: "Anteriore",
      passo: "Normale",
      tetto: "Basso",
      sensori_parcheggio: true,
      capacita_bagagliaio_valigie: 6,
      configurazione_sedili: "9 posti Combi",
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 90,
        valuta: "EUR",
        descrizione: "150 km inclusi / Assicurazione base — cauzione solo carta",
      },
    ],
    foto: [
      {
        id: "demo-primastar-frontale",
        url_pubblico: DEMO_IMAGES.nissanPrimastarFrontale,
        alt_text:
          "Noleggio pulmino 9 posti Nissan Primastar grigio metallizzato a Trieste presso LILO Autonoleggio in Viale Campi Elisi 38/b",
        titolo: "Nissan Primastar 9 posti noleggio pulmino Trieste",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-primastar-retro",
        url_pubblico: DEMO_IMAGES.nissanPrimastarRetro,
        alt_text:
          "Vista laterale e posteriore Nissan Primastar Combi 9 posti per viaggi di gruppo e vacanze a Trieste",
        titolo: "Noleggio Nissan Primastar Combi Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
      {
        id: "demo-primastar-guida",
        url_pubblico: DEMO_IMAGES.nissanPrimastarGuida,
        alt_text: "Posto di guida moderno, plancia ed ergonomia Nissan Primastar 9 posti",
        titolo: "Plancia e posto guida Nissan Primastar",
        didascalia: null,
        ordine: 2,
        is_copertina: false,
      },
      {
        id: "demo-primastar-interni",
        url_pubblico: DEMO_IMAGES.nissanPrimastarInterni,
        alt_text: "Abitacolo spazioso e configurazione sedili passeggeri Nissan Primastar 9 posti",
        titolo: "Interni comodi passeggeri Nissan Primastar 9 posti",
        didascalia: null,
        ordine: 3,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-toyota-proace-city",
    slug: "toyota-proace-city",
    targa: "GJ996JJ",
    marca: "Toyota",
    modello: "Proace City",
    versione: "L1 / Van",
    anno_immatricolazione: 2022,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 2,
    porte: 4,
    titolo_pubblico: "Noleggio Furgone Piccolo Toyota Proace City a Trieste",
    sottotitolo:
      "Agilità urbana e massimo spazio di carico per i tuoi piccoli trasporti in città.",
    descrizione_breve:
      "Noleggio Toyota Proace City a Trieste: furgone piccolo (~3,3–3,8 m³), compatto e agile per consegne e piccoli trasporti urbani. Ritiro in Viale Campi Elisi 38/b.",
    descrizione_completa:
      "Il Toyota Proace City è il furgone piccolo di LILO S.r.l. a Trieste: compatto e agile nel traffico cittadino, ideale per consegne veloci, piccoli trasporti urbani, attrezzature di lavoro o traslochi leggeri. Volume di carico circa 3,3 m³ (fino a 3,8 m³ con Smart Cargo), portata utile 583 kg. Noleggio flessibile, anche senza carta di credito per uso in città. Ritiro e riconsegna presso Viale Campi Elisi 38/b.",
    seo_title: "Noleggio Furgone Piccolo Trieste | Toyota Proace City - Lilo SRL",
    seo_description:
      "Cerchi un furgone piccolo ed economico a Trieste? Noleggia il Toyota Proace City da LILO SRL. Trasparenza, tariffe chiare e noleggio senza carta di credito!",
    seo_keywords: [
      "noleggio furgone piccolo trieste",
      "toyota proace city trieste",
      "furgone economico trieste",
    ],
    meta_robots: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.toyotaProaceCity,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Toyota Proace City — furgone piccolo (~3,3–3,8 m³) a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b.",
    ai_highlights: [
      "Dimensioni Compatte: Facile da guidare e parcheggiare anche nelle vie strette di Trieste.",
      "Ideale per Professionisti & Privati: Perfetto per consegne espresse, piccoli traslochi di scatole o trasporto strumenti.",
      "Consumi Ridotti: Categoria economica e dai bassi consumi di carburante.",
      "Noleggio Flessibile: Disponibile anche senza carta di credito.",
    ],
    ai_faq: [
      {
        q: "Per cosa è adatto il noleggio di un furgone piccolo come il Toyota Proace City?",
        a: "Il furgone piccolo è ideale per muoversi agevolmente nel centro di Trieste, trasportare piccoli elettrodomestici, scatoloni o attrezzatura da lavoro fino a circa 3,3-3,8 metri cubi di carico.",
      },
    ],
    ai_context: "Ritiro e riconsegna presso la sede LILO in Viale Campi Elisi 38/B, Trieste.",
    categoria: cat("furgoni-piccoli"),
    unita_disponibili: 2,
    specifiche_tecniche: specs({
      portata_kg: 583,
      volume_carico_mc: 3.3,
      volume_metri_cubi: 3.3,
      portata_utile_kg: 583,
      trazione: "Anteriore",
      passo: "Corto",
      tetto: "Basso",
      sensori_parcheggio: false,
      lunghezza_mm: 4403,
      larghezza_mm: 1848,
      vano_lunghezza_mm: 1817,
      vano_larghezza_mm: 1527,
      vano_altezza_mm: 1200,
      lunghezza_vano_mm: 1817,
      larghezza_vano_mm: 1527,
      altezza_vano_mm: 1200,
      larghezza_tra_passaruota_mm: 1229,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 50,
        valuta: "EUR",
        descrizione: "100 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      {
        id: "demo-proace-front",
        url_pubblico: DEMO_IMAGES.toyotaProaceCity,
        alt_text: "Noleggio Furgone Piccolo Toyota Proace City a Trieste - Lilo SRL",
        titolo: "Toyota Proace City noleggio furgone piccolo Trieste — frontale",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-proace-rear",
        url_pubblico: DEMO_IMAGES.toyotaProaceCityRear,
        alt_text: "Noleggio Furgone Piccolo Toyota Proace City a Trieste - Lilo SRL",
        titolo: "Toyota Proace City noleggio furgone piccolo Trieste — posteriore",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-furg-piccolo-1",
    slug: "fiat-doblo-cargo",
    targa: "FD789EF",
    marca: "Fiat",
    modello: "Doblò Cargo",
    versione: "1.6 Multijet",
    anno_immatricolazione: 2022,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 2,
    porte: 4,
    titolo_pubblico: "Fiat Doblò Cargo — Furgone piccolo Trieste",
    sottotitolo: "Compatto per consegne urbane",
    descrizione_breve: "Furgone piccolo diesel, 3,4 m³ di volume utile.",
    descrizione_completa: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: [],
    meta_robots: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary: "Fiat Doblò Cargo diesel, furgone piccolo a noleggio a Trieste.",
    ai_highlights: ["3,4 m³", "Diesel", "Compatto"],
    ai_faq: [],
    ai_context: null,
    categoria: cat("furgoni-piccoli"),
    specifiche_tecniche: specs({
      portata_kg: 750,
      volume_carico_mc: 3.4,
      volume_metri_cubi: 3.4,
      portata_utile_kg: 750,
      trazione: "Anteriore",
      passo: "Corto",
      tetto: "Basso",
      sensori_parcheggio: true,
      lunghezza_mm: 4406,
      larghezza_mm: 1832,
      altezza_mm: 1845,
      vano_lunghezza_mm: 1820,
      vano_larghezza_mm: 1714,
      vano_altezza_mm: 1305,
      lunghezza_vano_mm: 1820,
      larghezza_vano_mm: 1714,
      altezza_vano_mm: 1305,
      larghezza_tra_passaruota_mm: 1230,
    }),
    prezzi: [{ tipo_tariffa: "giornaliero", importo: 50, valuta: "EUR", descrizione: "100 km inclusi / Assicurazione base" }],
    foto: [
      demoFoto(
        "demo-furg-piccolo-foto",
        DEMO_IMAGES.furgonePiccolo,
        "Fiat Doblò Cargo — furgone piccolo noleggio Trieste",
      ),
    ],
  },
  {
    id: "00000000-0000-0000-0000-000000000001",
    slug: "ford-transit-l2h2",
    targa: "GG551RD",
    marca: "Ford",
    modello: "Transit",
    versione: "L2H2",
    anno_immatricolazione: 2021,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Ford Transit L2H2 — Noleggio furgone grande Trieste",
    sottotitolo: "Passo medio, tetto alto: ideale traslochi e merci",
    descrizione_breve:
      "Furgone Ford Transit L2H2 diesel, ideale per traslochi e trasporto merci a Trieste e provincia.",
    descrizione_completa:
      "Il Ford Transit L2H2 è un furgone capiente e affidabile, perfetto per traslochi, consegne e lavori artigianali. Disponibile presso la sede LILO di Trieste, Viale Campi Elisi 38/B.",
    seo_title: "Noleggio Ford Transit L2H2 Trieste | LILO Autonoleggio",
    seo_description:
      "Noleggia un Ford Transit L2H2 a Trieste. Furgone diesel, ampio vano di carico. Prenota online o chiama il 040 2471720.",
    seo_keywords: ["noleggio furgone trieste", "ford transit noleggio", "furgoni grandi trieste"],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: null,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Furgone Ford Transit L2H2 diesel disponibile a noleggio presso LILO S.r.l. a Trieste. Adatto a traslochi e trasporto merci.",
    ai_highlights: ["~10 m³", "Diesel", "Ideale traslochi", "Ritiro a Trieste"],
    ai_faq: [
      {
        q: "Quale patente serve per il Ford Transit?",
        a: "Patente B per i modelli fino a 3,5 t di massa complessiva.",
      },
      {
        q: "Dove ritiro il furgone?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/B, Trieste.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede.",
    categoria: cat("furgoni-grandi"),
    specifiche_tecniche: specs({
      portata_kg: 1166,
      volume_carico_mc: 10,
      volume_metri_cubi: 10,
      portata_utile_kg: 1166,
      trazione: "Anteriore",
      passo: "Medio",
      tetto: "Alto",
      sensori_parcheggio: true,
      lunghezza_mm: 5531,
      larghezza_mm: 2059,
      altezza_mm: 2470,
      vano_lunghezza_mm: 3044,
      vano_larghezza_mm: 1784,
      vano_altezza_mm: 1886,
      lunghezza_vano_mm: 3044,
      larghezza_vano_mm: 1784,
      altezza_vano_mm: 1886,
    }),
    prezzi: [{ tipo_tariffa: "giornaliero", importo: 55, valuta: "EUR", descrizione: "100 km inclusi / Assicurazione base" }],
    foto: [
      demoFoto(
        "demo-foto-1",
        "/images/veicoli/ford-transit-gg551rd-noleggio-furgoni-grandi-trieste.webp",
        "Ford Transit L2H2 — furgone bianco per noleggio a Trieste",
      ),
      {
        id: "demo-foto-2",
        url_pubblico: "/images/veicoli/ford-transit-gg551rd-posteriore-trieste.webp",
        alt_text: "Vano di carico Ford Transit L2H2 — noleggio furgone Trieste",
        titolo: "Vano di carico",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-citroen-jumpy-l1h1",
    slug: "citroen-jumpy-l1h1",
    targa: "FR523SW",
    marca: "Citroën",
    modello: "Jumpy",
    versione: "L1 H1",
    anno_immatricolazione: 2024,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Citroën Jumpy L1 H1 — Noleggio furgone medio Trieste",
    sottotitolo: "Furgone medio diesel, ideale per lavoro e consegne",
    descrizione_breve:
      "Noleggio Citroën Jumpy L1 H1 a Trieste: 5,3 m³, portata 1.028 kg, vano interno 2.512×1.258×1.397 mm. Targa FR523SW, immatricolazione 2024.",
    descrizione_completa:
      "Il Citroën Jumpy L1 H1 (targa FR523SW) è un furgone medio diesel con vano interno da 2.512 mm di lunghezza, 1.258 mm tra i passaruota e 1.397 mm di altezza, per un volume utile di 5,3 m³ e portata utile di 1.028 kg. Disponibile presso LILO S.r.l. a Trieste, Viale Campi Elisi 38/B.",
    seo_title: "Noleggio Citroën Jumpy L1 H1 Trieste | LILO Autonoleggio",
    seo_description:
      "Noleggia il Citroën Jumpy L1 H1 (5,3 m³) a Trieste con LILO S.r.l. Furgone medio diesel, targa FR523SW, ritiro in sede.",
    seo_keywords: ["noleggio furgone medio trieste", "citroen jumpy noleggio", "FR523SW"],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.citroenJumpyFr523sw,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Citroën Jumpy L1 H1 diesel, 5,3 m³, vano 2.512 mm — noleggio a Trieste presso LILO S.r.l. Targa FR523SW, anno 2024.",
    ai_highlights: ["5,3 m³", "Diesel", "Portata 1.028 kg", "Vano 2.512 mm", "Trieste"],
    ai_faq: [
      {
        q: "Quale patente serve per il Citroën Jumpy?",
        a: "Patente B per i modelli fino a 3,5 t di massa complessiva.",
      },
      {
        q: "Dove ritiro il furgone?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/B, Trieste.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede.",
    categoria: cat("furgoni-medi"),
    specifiche_tecniche: specs({
      portata_kg: 1028,
      volume_carico_mc: 5.3,
      volume_metri_cubi: 5.3,
      portata_utile_kg: 1028,
      trazione: "Anteriore",
      passo: "Corto",
      tetto: "Basso",
      sensori_parcheggio: true,
      lunghezza_mm: 4983,
      larghezza_mm: 1920,
      altezza_mm: 1895,
      vano_lunghezza_mm: 2512,
      vano_larghezza_mm: 1636,
      vano_altezza_mm: 1397,
      lunghezza_vano_mm: 2512,
      larghezza_vano_mm: 1636,
      altezza_vano_mm: 1397,
      larghezza_tra_passaruota_mm: 1258,
    }),
    prezzi: [{ tipo_tariffa: "giornaliero", importo: 55, valuta: "EUR", descrizione: "100 km inclusi / Assicurazione base" }],
    foto: [
      demoFoto(
        "demo-citroen-jumpy-copertina",
        DEMO_IMAGES.citroenJumpyFr523sw,
        "Noleggio Furgone Medio Citroën Jumpy LILO Autonoleggio Trieste - Fiancata con targa FR523SW",
      ),
      {
        id: "demo-citroen-jumpy-posteriore",
        url_pubblico: DEMO_IMAGES.citroenJumpyFr523swPosteriore,
        alt_text:
          "Noleggio Furgone Medio Citroën Jumpy LILO Autonoleggio Trieste - Posteriore con targa FR523SW",
        titolo: "Vista posteriore",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-opel-vivaro",
    slug: "opel-vivaro",
    targa: "n.d.",
    marca: "Opel",
    modello: "Vivaro",
    versione: "Van",
    anno_immatricolazione: 2015,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Opel Vivaro Van — Furgone medio Trieste",
    sottotitolo: "Furgone medio con barre portatutto, ideale città e piccoli traslochi",
    descrizione_breve:
      "Noleggio Opel Vivaro Van a Trieste: furgone medio con barre sul tetto, vano capiente e guida agevole. Ritiro in Viale Campi Elisi 38/b.",
    descrizione_completa:
      "L'Opel Vivaro Van è il furgone medio di LILO S.r.l.: bilanciamento ideale tra vano di carico e manovrabilità nel traffico di Trieste. Equipaggiato con barre portatutto per scale, tubi e carichi lunghi. Adatto a professionisti e privati per piccoli traslochi o lavoro quotidiano. Ritiro e riconsegna presso la sede di Viale Campi Elisi 38/b a Trieste.",
    seo_title: "Noleggio Opel Vivaro Trieste | Furgoni Medi | LILO Autonoleggio",
    seo_description:
      "Noleggia l'Opel Vivaro Van a Trieste (Viale Campi Elisi 38/b). Furgone medio con barre portatutto, ideale trasporti e piccoli traslochi. LILO.",
    seo_keywords: [
      "noleggio opel vivaro trieste",
      "furgone medio trieste",
      "barre portatutto noleggio",
      "viale campi elisi noleggio",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.opelVivaro,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Opel Vivaro Van — furgone medio con barre portatutto a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b.",
    ai_highlights: [
      "📦 Dimensioni Intermedie Ideali: Bilanciamento perfetto tra vano di carico capiente e facilità di guida nel traffico cittadino.",
      "🪜 Barre Portatutto Integrate: Equipaggiato con barre sul tetto per il trasporto pratico di scale, tubi o carichi lunghi.",
      "💼 Eccellente per Professionisti e Privati: Ottimo sia per piccoli traslochi fai-da-te che per esigenze lavorative giornaliere.",
      "📍 Ritiro e Consegna in Sede: Presso la sede LILO S.r.l. di Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "Dove ritiro l'Opel Vivaro?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
      {
        q: "Ha le barre sul tetto?",
        a: "Sì: barre portatutto integrate, utili per scale, tubi e carichi lunghi.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("furgoni-medi"),
    specifiche_tecniche: specs({
      portata_kg: 1000,
      volume_carico_mc: 5.2,
      volume_metri_cubi: 5.2,
      portata_utile_kg: 1000,
      trazione: "Anteriore",
      passo: "Medio",
      tetto: "Basso",
      sensori_parcheggio: true,
      vano_lunghezza_mm: 2537,
      vano_larghezza_mm: 1662,
      vano_altezza_mm: 1387,
      lunghezza_vano_mm: 2537,
      larghezza_vano_mm: 1662,
      altezza_vano_mm: 1387,
      larghezza_tra_passaruota_mm: 1268,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 55,
        valuta: "EUR",
        descrizione: "100 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      {
        id: "demo-opel-vivaro-copertina",
        url_pubblico: DEMO_IMAGES.opelVivaro,
        alt_text:
          "Noleggio furgone medio Opel Vivaro bianco con barre sul tetto a Trieste presso LILO Autonoleggio in Viale Campi Elisi 38/b",
        titolo: "Opel Vivaro noleggio furgone medio Trieste",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-opel-vivaro-retro",
        url_pubblico: DEMO_IMAGES.opelVivaroRetro,
        alt_text:
          "Vista posteriore e laterale furgone Opel Vivaro per trasporto merci e traslochi a Trieste",
        titolo: "Noleggio Opel Vivaro furgone commerciale Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-ford-transit-l2h2-citta",
    slug: "ford-transit-l2h2-citta",
    targa: "DV344HD",
    marca: "Ford",
    modello: "Transit",
    versione: "L2H2",
    anno_immatricolazione: 2012,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Ford Transit L2H2 — Furgone grande uso città Trieste",
    sottotitolo: "Ampia capacità di carico con manovrabilità urbana",
    descrizione_breve:
      "Noleggio Ford Transit L2H2 a Trieste: furgone grande uso città, tetto alto e passo medio. Ritiro in Viale Campi Elisi 38/b. Targa DV344HD.",
    descrizione_completa:
      "Il Ford Transit L2H2 (targa DV344HD) è il furgone grande uso città di LILO S.r.l.: dimensioni L2H2 ideali per traslochi voluminosi e trasporto merci, con ottima manovrabilità in ambito urbano. Tetto alto (H2) e passo medio (L2) per stivare carichi alti, mobili e bancali. Ritiro e riconsegna presso la sede di Viale Campi Elisi 38/b a Trieste.",
    seo_title: "Noleggio Ford Transit L2H2 Trieste | Furgoni Grandi Città | LILO",
    seo_description:
      "Noleggia il Ford Transit L2H2 a Trieste (Viale Campi Elisi 38/b). Furgone grande uso città, ampia capacità di carico. LILO Autonoleggio.",
    seo_keywords: [
      "noleggio ford transit trieste",
      "furgoni grandi città trieste",
      "viale campi elisi noleggio",
      "DV344HD",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.fordTransitL2h2,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Ford Transit L2H2 — furgone grande uso città a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b. Targa DV344HD.",
    ai_highlights: [
      "Categoria Grande / Città: Dimensioni L2H2 ideali per traslochi voluminosi e trasporto merci, mantenendo un'ottima manovrabilità urbana.",
      "Ampia Capacità di Carico: Tetto alto (H2) e passo medio (L2) per stivare carichi alti, mobili e bancali senza problemi.",
      "Ritiro in Sede: Disponibile per il ritiro diretto presso la sede di Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "Dove ritiro il Ford Transit L2H2?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
      {
        q: "È adatto ai traslochi in città?",
        a: "Sì: configurazione L2H2 con ampia capacità di carico e buona manovrabilità urbana (categoria Grandi / Uso Città).",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("furgoni-grandi-citta"),
    specifiche_tecniche: specs({
      portata_kg: 1200,
      volume_carico_mc: 10,
      volume_metri_cubi: 10,
      portata_utile_kg: 1200,
      trazione: "Anteriore",
      passo: "Medio",
      tetto: "Alto",
      sensori_parcheggio: true,
      vano_lunghezza_mm: 2949,
      vano_larghezza_mm: 1762,
      vano_altezza_mm: 1886,
      lunghezza_vano_mm: 2949,
      larghezza_vano_mm: 1762,
      altezza_vano_mm: 1886,
      larghezza_tra_passaruota_mm: 1390,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 55,
        valuta: "EUR",
        descrizione: "50 km inclusi / Assicurazione base — uso città",
      },
    ],
    foto: [
      {
        id: "demo-ford-transit-l2h2-copertina",
        url_pubblico: DEMO_IMAGES.fordTransitL2h2,
        alt_text:
          "Noleggio furgone Ford Transit L2H2 presso LILO Autonoleggio in Viale Campi Elisi 38/b Trieste",
        titolo: "Ford Transit L2H2 noleggio furgoni grandi Trieste Viale Campi Elisi",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-ford-transit-l2h2-retro",
        url_pubblico: DEMO_IMAGES.fordTransitL2h2Retro,
        alt_text:
          "Vista posteriore Ford Transit L2H2 per traslochi e trasporto merci a Trieste Viale Campi Elisi",
        titolo: "Noleggio Ford Transit L2H2 Categoria Grande Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-citroen-jumper-l2h2",
    slug: "citroen-jumper-l2h2",
    targa: "FT248AN",
    marca: "Citroën",
    modello: "Jumper",
    versione: "L2H2",
    anno_immatricolazione: 2016,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Citroën Jumper L2H2 — Furgone grande uso città Trieste",
    sottotitolo: "Passo medio, tetto alto: ~11,5 m³ con manovrabilità urbana",
    descrizione_breve:
      "Noleggio Citroën Jumper L2H2 a Trieste: furgone grande uso città (~11,5 m³), tetto alto e passo medio. Ritiro in Viale Campi Elisi 38/b. Targa FT248AN.",
    descrizione_completa:
      "Il Citroën Jumper L2H2 (targa FT248AN) è il furgone grande uso città di LILO S.r.l.: configurazione L2H2 con passo medio e tetto alto per circa 11,5 m³ di volume utile, ideale per traslochi e trasporto merci ingombranti senza rinunciare alla manovrabilità nel traffico di Trieste. Altezza interna che consente di stare in piedi nel vano di carico. Ritiro e riconsegna presso la sede di Viale Campi Elisi 38/b a Trieste.",
    seo_title: "Noleggio Citroën Jumper L2H2 Trieste | Furgoni Grandi Città | LILO",
    seo_description:
      "Noleggia il Citroën Jumper L2H2 a Trieste (Viale Campi Elisi 38/b). Furgone grande uso città ~11,5 m³, ideale traslochi. LILO Autonoleggio.",
    seo_keywords: [
      "noleggio citroen jumper trieste",
      "furgone l2h2 trieste",
      "furgoni grandi città trieste",
      "viale campi elisi noleggio",
      "FT248AN",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.citroenJumperL2h2,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Citroën Jumper L2H2 — furgone grande uso città (~11,5 m³) a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b. Targa FT248AN.",
    ai_highlights: [
      "📦 Configurazione L2H2: Passo medio e tetto alto per una capacità di carico ottimale (circa 11,5 m³) mantenendo un'ottima manovrabilità nel traffico urbano.",
      "🚛 Perfetto per Traslochi e Trasporto Merci: Altezza interna che consente di stare in piedi nel vano di carico e caricare merci ingombranti o elettrodomestici.",
      "🏙️ Uso Città e Provincia: Dimensioni bilanciate ideali per la viabilità e i parcheggi di Trieste e dintorni.",
      "📍 Ritiro e Consegna in Sede: Presso la sede LILO S.r.l. di Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "Dove ritiro il Citroën Jumper L2H2?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
      {
        q: "Quanto volume di carico ha?",
        a: "Circa 11,5 m³ in configurazione L2H2 (passo medio, tetto alto), ideale per traslochi e merci ingombranti.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("furgoni-grandi-citta"),
    specifiche_tecniche: specs({
      portata_kg: 1200,
      volume_carico_mc: 11.5,
      volume_metri_cubi: 11.5,
      portata_utile_kg: 1200,
      trazione: "Anteriore",
      passo: "Medio",
      tetto: "Alto",
      sensori_parcheggio: true,
      vano_lunghezza_mm: 3120,
      vano_larghezza_mm: 1870,
      vano_altezza_mm: 1932,
      lunghezza_vano_mm: 3120,
      larghezza_vano_mm: 1870,
      altezza_vano_mm: 1932,
      larghezza_tra_passaruota_mm: 1422,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 55,
        valuta: "EUR",
        descrizione: "50 km inclusi / Assicurazione base — uso città",
      },
    ],
    foto: [
      {
        id: "demo-citroen-jumper-l2h2-copertina",
        url_pubblico: DEMO_IMAGES.citroenJumperL2h2,
        alt_text:
          "Noleggio furgone grande Citroën Jumper L2H2 bianco a Trieste presso LILO Autonoleggio in Viale Campi Elisi 38/b",
        titolo: "Citroën Jumper L2H2 noleggio furgoni Trieste",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-citroen-jumper-l2h2-retro",
        url_pubblico: DEMO_IMAGES.citroenJumperL2h2Retro,
        alt_text:
          "Vista laterale e posteriore furgone Citroën Jumper L2H2 per traslochi e merci a Trieste",
        titolo: "Noleggio furgone L2H2 uso città Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-fiat-ducato-l1h1",
    slug: "fiat-ducato-l1h1",
    targa: "FG289KB",
    marca: "Fiat",
    modello: "Ducato",
    versione: "L1H1",
    anno_immatricolazione: 2018,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Fiat Ducato L1H1 — Furgone grande Trieste",
    sottotitolo: "Con rampa moto e vano lavabile HACCP",
    descrizione_breve:
      "Noleggio Fiat Ducato L1H1 a Trieste: rampa di carico moto in alluminio, rivestimento interno lavabile idoneo HACCP e vano ottimizzato. Targa FG289KB.",
    descrizione_completa:
      "Il Fiat Ducato L1H1 (targa FG289KB) è un furgone grande ideale per chi deve caricare moto, attrezzature o merci alimentari. È dotato di rampa di carico rinforzata in alluminio antiscivolo, vano interno completamente rivestito con materiali lavabili e igienizzabili conformi alle normative HACCP, fondo rinforzato e passaruota protetti. Disponibile presso LILO S.r.l. a Trieste, Viale Campi Elisi 38/B.",
    seo_title: "Noleggio Fiat Ducato L1H1 Trieste | Rampa moto e HACCP | LILO",
    seo_description:
      "Noleggia il Fiat Ducato L1H1 a Trieste con rampa di carico moto e rivestimento lavabile HACCP. Ritiro in sede LILO S.r.l.",
    seo_keywords: [
      "noleggio fiat ducato trieste",
      "furgone rampa moto",
      "furgone haccp trieste",
      "FG289KB",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.fiatDucatoL1h1,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Fiat Ducato L1H1 con rampa moto e vano lavabile HACCP — noleggio a Trieste presso LILO S.r.l. Targa FG289KB.",
    ai_highlights: [
      "Rampa di carico moto: Dotato di rampa rinforzata in alluminio antiscivolo per il carico/scarico agevole e sicuro di motocicli.",
      "Rivestimento lavabile idoneo HACCP: Vano interno completamente rivestito con materiali lavabili e igienizzabili, conforme alle normative HACCP per il trasporto alimentare, catering e merci fresche.",
      "Vano ottimizzato: Fondo rinforzato e passaruota protetti per massima versatilità tra merci, moto e alimenti.",
    ],
    ai_faq: [
      {
        q: "Il Fiat Ducato ha la rampa per caricare le moto?",
        a: "Sì: è dotato di rampa rinforzata in alluminio antiscivolo per carico e scarico sicuri di motocicli.",
      },
      {
        q: "Il vano è idoneo al trasporto alimentare HACCP?",
        a: "Sì: l’interno è completamente rivestito con materiali lavabili e igienizzabili, conformi alle normative HACCP.",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede.",
    categoria: cat("furgoni-grandi"),
    specifiche_tecniche: specs({
      portata_kg: 1100,
      volume_carico_mc: 8,
      volume_metri_cubi: 8,
      portata_utile_kg: 1100,
      trazione: "Anteriore",
      passo: "Corto",
      tetto: "Basso",
      sensori_parcheggio: true,
      vano_lunghezza_mm: 2670,
      vano_larghezza_mm: 1870,
      vano_altezza_mm: 1662,
      lunghezza_vano_mm: 2670,
      larghezza_vano_mm: 1870,
      altezza_vano_mm: 1662,
      larghezza_tra_passaruota_mm: 1422,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 60,
        valuta: "EUR",
        descrizione: "100 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      demoFoto(
        "demo-fiat-ducato-copertina",
        DEMO_IMAGES.fiatDucatoL1h1,
        "Noleggio Fiat Ducato L1H1 Trieste — esterno principale LILO S.r.l.",
      ),
      {
        id: "demo-fiat-ducato-rampa",
        url_pubblico: DEMO_IMAGES.fiatDucatoL1h1Rampa,
        alt_text:
          "Fiat Ducato L1H1 con rampa di carico per moto e lavabile per trasporto alimentari HACCP",
        titolo: "Noleggio furgone Fiat Ducato L1H1 con rampa moto e idoneità HACCP Trieste",
        didascalia: "Rampa alluminio antiscivolo e vano rivestito HACCP",
        ordine: 1,
        is_copertina: false,
      },
      {
        id: "demo-fiat-ducato-posteriore",
        url_pubblico: DEMO_IMAGES.fiatDucatoL1h1Posteriore,
        alt_text: "Fiat Ducato L1H1 posteriore — noleggio furgone grande Trieste LILO",
        titolo: "Vista posteriore",
        didascalia: null,
        ordine: 2,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-furg-grande-1",
    slug: "iveco-daily-35-12",
    targa: "EV840AM",
    marca: "Iveco",
    modello: "Daily",
    versione: "L2H2 / 35S13",
    anno_immatricolazione: 2014,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Iveco Daily L2H2 — Furgone grande uso città Trieste",
    sottotitolo: "Passo medio, tetto alto: ~10,8 m³ con manovrabilità urbana",
    descrizione_breve:
      "Noleggio Iveco Daily L2H2 a Trieste: furgone grande uso città (~10,8 m³), portata 1420 kg. Ritiro in Viale Campi Elisi 38/b. Targa EV840AM.",
    descrizione_completa: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: [],
    meta_robots: null,
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.furgoneGrande,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Iveco Daily L2H2 35S13 — furgone grande uso città (~10,8 m³, portata 1420 kg) a noleggio a Trieste.",
    ai_highlights: ["L2H2", "~10,8 m³", "Portata 1420 kg", "Uso città"],
    ai_faq: [],
    ai_context: null,
    categoria: cat("furgoni-grandi-citta"),
    specifiche_tecniche: specs({
      portata_kg: 1420,
      volume_carico_mc: 10.8,
      volume_metri_cubi: 10.8,
      portata_utile_kg: 1420,
      trazione: "Posteriore",
      passo: "Medio",
      tetto: "Alto",
      sensori_parcheggio: true,
      lunghezza_mm: 5401,
      larghezza_mm: 1996,
      vano_lunghezza_mm: 3130,
      vano_larghezza_mm: 1800,
      vano_altezza_mm: 1900,
      lunghezza_vano_mm: 3130,
      larghezza_vano_mm: 1800,
      altezza_vano_mm: 1900,
      larghezza_tra_passaruota_mm: 1320,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 55,
        valuta: "EUR",
        descrizione: "50 km inclusi / Assicurazione base — uso città",
      },
    ],
    foto: [
      {
        id: "demo-iveco-daily-front",
        url_pubblico: DEMO_IMAGES.furgoneGrande,
        alt_text: "Noleggio Furgone Grande Uso Città Iveco Daily L2H2 a Trieste - Lilo SRL",
        titolo: "Iveco Daily L2H2 noleggio furgoni grandi uso città Trieste — frontale",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-iveco-daily-rear",
        url_pubblico: DEMO_IMAGES.furgoneGrandeRetro,
        alt_text: "Noleggio Furgone Grande Uso Città Iveco Daily L2H2 a Trieste - Lilo SRL",
        titolo: "Iveco Daily L2H2 noleggio furgoni grandi uso città Trieste — posteriore",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
  {
    id: "demo-peugeot-boxer-l3h3",
    slug: "peugeot-boxer-l3h3",
    targa: "GB762PM",
    marca: "Peugeot",
    modello: "Boxer",
    versione: "L3H3",
    anno_immatricolazione: 2018,
    colore: "Bianco",
    alimentazione: "Diesel",
    cambio: "Manuale",
    posti: 3,
    porte: 4,
    titolo_pubblico: "Peugeot Boxer L3H3 — Furgone extra large Trieste",
    sottotitolo: "Massimo volume di carico con tetto super alto",
    descrizione_breve:
      "Noleggio Peugeot Boxer L3H3 a Trieste: furgone extra large (~15 m³), tetto super alto e passo lungo. Ritiro in Viale Campi Elisi 38/b.",
    descrizione_completa:
      "Il Peugeot Boxer L3H3 è il furgone extra large di LILO S.r.l.: configurazione L3H3 con circa 15 m³ di volume utile, tetto super alto e passo lungo per traslochi impegnativi e carichi voluminosi. Ideale per arredi alti, mobilio in verticale e carichi industriali. Ritiro e riconsegna presso la sede di Viale Campi Elisi 38/b a Trieste.",
    seo_title: "Noleggio Peugeot Boxer L3H3 Trieste | Furgoni XL | LILO",
    seo_description:
      "Noleggia il Peugeot Boxer L3H3 a Trieste (Viale Campi Elisi 38/b). Furgone extra large ~15 m³, tetto super alto. LILO Autonoleggio.",
    seo_keywords: [
      "noleggio peugeot boxer trieste",
      "furgone xl trieste",
      "furgone l3h3 trieste",
    ],
    meta_robots: "index, follow",
    canonical_url: null,
    og_title: null,
    og_description: null,
    og_image_url: DEMO_IMAGES.peugeotBoxerL3h3,
    twitter_title: null,
    twitter_description: null,
    json_ld: null,
    ai_summary:
      "Peugeot Boxer L3H3 — furgone extra large (~15 m³) a noleggio a Trieste presso LILO S.r.l., Viale Campi Elisi 38/b.",
    ai_highlights: [
      "📦 Configurazione Extra Large L3H3: Volume di carico massimo (circa 15 m³) con tetto super alto ed estensione in lunghezza.",
      "🐘 Capienza Senza Compromessi: Permette di caricare arredi voluminosi, mobilio alto in verticale e carichi industriali ingombranti.",
      "🛠️ Ideale per Traslochi Impegnativi: Massimizza l'efficienza dei viaggi per aziende, artigiani e grandi traslochi privati.",
      "📍 Ritiro e Consegna in Sede: Presso la sede LILO S.r.l. di Viale Campi Elisi 38/b a Trieste.",
    ],
    ai_faq: [
      {
        q: "Dove ritiro il Peugeot Boxer L3H3?",
        a: "Presso la sede LILO in Viale Campi Elisi 38/b, Trieste.",
      },
      {
        q: "Quanto volume di carico ha?",
        a: "Circa 15 m³ in configurazione L3H3 (passo lungo, tetto super alto).",
      },
    ],
    ai_context: "Servizio di noleggio a Trieste e provincia. Ritiro in sede Viale Campi Elisi 38/b.",
    categoria: cat("furgoni-xl"),
    specifiche_tecniche: specs({
      portata_kg: 1400,
      volume_carico_mc: 15,
      volume_metri_cubi: 15,
      portata_utile_kg: 1400,
      trazione: "Anteriore",
      passo: "Lungo",
      tetto: "Super alto",
      sensori_parcheggio: true,
      vano_lunghezza_mm: 3705,
      vano_larghezza_mm: 1870,
      vano_altezza_mm: 2172,
      lunghezza_vano_mm: 3705,
      larghezza_vano_mm: 1870,
      altezza_vano_mm: 2172,
      larghezza_tra_passaruota_mm: 1422,
    }),
    prezzi: [
      {
        tipo_tariffa: "giornaliero",
        importo: 70,
        valuta: "EUR",
        descrizione: "100 km inclusi / Assicurazione base",
      },
    ],
    foto: [
      {
        id: "demo-boxer-l3h3-copertina",
        url_pubblico: DEMO_IMAGES.peugeotBoxerL3h3,
        alt_text:
          "Noleggio furgone gran volume Peugeot Boxer L3H3 bianco a Trieste presso LILO Autonoleggio in Viale Campi Elisi 38/b",
        titolo: "Peugeot Boxer L3H3 noleggio furgoni extra large Trieste",
        didascalia: null,
        ordine: 0,
        is_copertina: true,
      },
      {
        id: "demo-boxer-l3h3-retro",
        url_pubblico: DEMO_IMAGES.peugeotBoxerL3h3Retro,
        alt_text:
          "Vista laterale e posteriore furgone Peugeot Boxer L3H3 per traslochi voluminosi a Trieste",
        titolo: "Noleggio furgone L3H3 tetto super alto Trieste",
        didascalia: null,
        ordine: 1,
        is_copertina: false,
      },
    ],
  },
];

/** @deprecated Usare DEMO_VEICOLI[3] — mantenuto per compatibilità */
export const DEMO_VEICOLO = DEMO_VEICOLI.find((v) => v.slug === "ford-transit-l2h2-citta")!;

export const DEMO_SLUGS = DEMO_VEICOLI.map((v) => v.slug);

export function isDemoMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "";
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
  if (process.env.NEXT_PUBLIC_DEMO_MODE === "true") return true;
  return !url || url.includes("your-project") || !key || key.includes("your-anon");
}
